project:
  type: website
  output-dir: _site

website:
  title: "Distinction Centrality"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Theory & Analysis"
        href: analysis.qmd
      - text: "Distinction Function"
        href: functions.qmd
      - text: "Examples"
        href: examples.qmd
    right:
      - icon: github
        href: https://github.com/olizardo/Jilbert-Distinction-Centrality
        text: "Repository"
  sidebar: false

format:
  html:
    theme: cosmo
    toc: true
