on:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev libxml2-dev libcurl4-openssl-dev libssl-dev

      - name: Install Dependencies
        run: |
          install.packages(c("igraph", "ggraph", "here", "dplyr", "kableExtra", "ggpubr", "patchwork", "rmarkdown", "readr", "digest", "xfun", "htmltools", "rlang", "fastmap", "jsonlite", "generics", "R6", "ggplot2", "remotes", "networkdata"))
        shell: Rscript {0}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _site/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
